import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../auth/user_profile_service.dart';
import '../firebase/bootstrap_service.dart';
import '../l10n/app_localizations.dart';

class FirebaseSmokeTestScreen extends StatefulWidget {
  const FirebaseSmokeTestScreen({super.key});

  @override
  State<FirebaseSmokeTestScreen> createState() =>
      _FirebaseSmokeTestScreenState();
}

class _FirebaseSmokeTestScreenState extends State<FirebaseSmokeTestScreen> {
  final List<String> _logs = <String>[];
  bool _busy = false;

  String? _uid;
  String? _email;
  String _role = 'unknown';

  @override
  void initState() {
    super.initState();
    _loadHeaderInfo();
  }

  Future<void> _loadHeaderInfo() async {
    final user = FirebaseAuth.instance.currentUser;
    _uid = user?.uid;
    _email = user?.email;
    if (_uid == null || _uid!.isEmpty) {
      if (mounted) setState(() {});
      return;
    }
    try {
      final userDoc = await FirebaseFirestore.instance
          .doc('users/${_uid!}')
          .get();
      _role = (userDoc.data()?['role'] ?? 'unknown').toString();
    } catch (_) {
      _role = 'unknown';
    }
    if (mounted) setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context)!;
    if (!kDebugMode) {
      return Scaffold(
        body: Center(child: Text(AppLocalizations.of(context)!.nurInDebugBuilds)),
      );
    }

    return FutureBuilder<AppUserRole>(
      future: UserProfileService().getMyRole(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.data != AppUserRole.admin) {
          return Scaffold(
            appBar: AppBar(title: Text(l.noAccess)),
            body: const Center(
              child: Text('Nur fuer Admins verfuegbar.'),
            ),
          );
        }
        return _buildContent(context);
      },
    );
  }

  Widget _buildContent(BuildContext context) {
    final l = AppLocalizations.of(context)!;
    return Scaffold(
      appBar: AppBar(title: Text(l.adminFirebaseSmokeTest)),
      body: Column(
        children: [
          _headerCard(),
          Expanded(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
              children: [
                _actionButton('Bootstrap prüfen', _bootstrapCheck),
                _actionButton(
                  'Test: write+read timeline',
                  () => _testWriteRead(
                    collection: 'timeline',
                    payload: <String, dynamic>{
                      'title': 'smoke timeline',
                      'state': 'planned',
                    },
                  ),
                ),
                _actionButton(
                  'Test: write+read wounds meta',
                  () => _testWriteRead(
                    collection: 'wounds',
                    payload: <String, dynamic>{
                      'pain': 2,
                      'note': 'smoke wound',
                      'metadata': <String, dynamic>{'smoke': true},
                    },
                  ),
                ),
                _actionButton(
                  'Test: write+read pain',
                  () => _testWriteRead(
                    collection: 'pain',
                    payload: <String, dynamic>{
                      'painLevel': 3,
                      'note': 'smoke pain',
                      'occurredAt': DateTime.now().toIso8601String(),
                    },
                  ),
                ),
                _actionButton(
                  'Test: write+read appointments',
                  () => _testWriteRead(
                    collection: 'appointments',
                    payload: <String, dynamic>{
                      'title': 'smoke appointment',
                      'notes': 'generated by smoke test',
                      'startAt': DateTime.now()
                          .add(const Duration(days: 1))
                          .toIso8601String(),
                    },
                  ),
                ),
                _actionButton(
                  'Test: write+read documents meta',
                  () => _testWriteRead(
                    collection: 'documents',
                    payload: <String, dynamic>{
                      'title': 'smoke document',
                      'type': 'sonstiges',
                      'storagePath': 'patients/<uid>/documents/smoke.pdf',
                    },
                  ),
                ),
                _actionButton(
                  'Test: forbidden read (other uid)',
                  _testForbiddenRead,
                ),
                const SizedBox(height: 16),
                _logBox(),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _headerCard() {
    return Card(
      margin: const EdgeInsets.all(16),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('uid: ${_uid ?? 'nicht eingeloggt'}'),
            Text('email: ${_email ?? 'nicht verfügbar'}'),
            Text('role: $_role'),
            if (_busy)
              const Padding(
                padding: EdgeInsets.only(top: 8),
                child: LinearProgressIndicator(),
              ),
          ],
        ),
      ),
    );
  }

  Widget _actionButton(String label, Future<void> Function() onPressed) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: FilledButton(
        onPressed: _busy
            ? null
            : () async {
                await _run(label, onPressed);
              },
        child: Align(alignment: Alignment.centerLeft, child: Text(label)),
      ),
    );
  }

  Widget _logBox() {
    final l = AppLocalizations.of(context)!;
    return Container(
      constraints: const BoxConstraints(minHeight: 200),
      decoration: BoxDecoration(
        border: Border.all(color: Colors.grey.shade300),
        borderRadius: BorderRadius.circular(8),
      ),
      padding: const EdgeInsets.all(10),
      child: _logs.isEmpty
          ? Text(l.adminLogsAppear)
          : SelectableText(_logs.join('\n')),
    );
  }

  Future<void> _run(String label, Future<void> Function() fn) async {
    setState(() => _busy = true);
    _log('--- $label ---');
    try {
      await fn();
    } catch (error) {
      _log('ERROR: $error');
    } finally {
      if (mounted) {
        setState(() => _busy = false);
      }
    }
  }

  Future<void> _bootstrapCheck() async {
    final uid = _requireUid();
    final user = FirebaseAuth.instance.currentUser!;
    final bootstrap = BootstrapService();
    await bootstrap.ensureUserDocExists(
      uid,
      email: user.email,
      displayName: user.displayName,
      roleDefault: 'patient',
    );
    await bootstrap.ensurePatientRootExists(uid);

    final userDoc = await FirebaseFirestore.instance.doc('users/$uid').get();
    final patientDoc = await FirebaseFirestore.instance
        .doc('patients/$uid')
        .get();
    _log('users/$uid exists: ${userDoc.exists}');
    _log('patients/$uid exists: ${patientDoc.exists}');
    _log('SUCCESS: bootstrap check');
    await _loadHeaderInfo();
  }

  Future<void> _testWriteRead({
    required String collection,
    required Map<String, dynamic> payload,
  }) async {
    final uid = _requireUid();
    final id = 'test_${DateTime.now().millisecondsSinceEpoch}';
    final docRef = FirebaseFirestore.instance.doc(
      'patients/$uid/$collection/$id',
    );
    final data = <String, dynamic>{
      'ownerId': uid,
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'clientUpdatedAt': DateTime.now().toIso8601String(),
      ...payload,
    };

    try {
      await docRef.set(data);
      final readBack = await docRef.get();
      _log('write path: ${docRef.path}');
      _log('read exists: ${readBack.exists}');
      _log('SUCCESS: $collection write+read');
    } on FirebaseException catch (e) {
      _log('ERROR $collection: ${e.code} ${e.message ?? ''}');
    }
  }

  Future<void> _testForbiddenRead() async {
    final uid = _requireUid();
    final forbiddenUid = uid == 'FORBIDDEN_TEST_UID'
        ? 'FORBIDDEN_TEST_UID_2'
        : 'FORBIDDEN_TEST_UID';
    final docRef = FirebaseFirestore.instance.doc(
      'patients/$forbiddenUid/timeline/forbidden_probe',
    );

    try {
      await docRef.get();
      _log('WARN: forbidden read unexpectedly succeeded (${docRef.path})');
    } on FirebaseException catch (e) {
      if (e.code == 'permission-denied') {
        _log('SUCCESS: permission-denied as expected');
      } else {
        _log(
          'ERROR: expected permission-denied, got ${e.code} ${e.message ?? ''}',
        );
      }
    }
  }

  String _requireUid() {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid == null || uid.trim().isEmpty) {
      throw Exception('Nicht eingeloggt (keine uid).');
    }
    return uid;
  }

  void _log(String message) {
    final time = TimeOfDay.now().format(context);
    setState(() => _logs.insert(0, '[$time] $message'));
  }
}
