import 'timeline_engine.dart';

class TaskTemplate {
  const TaskTemplate({
    required this.templateId,
    required this.type,
    required this.title,
    required this.subtitle,
    required this.priority,
    required this.deeplinkRoute,
    required this.phase,
    required this.relativeDay,
    required this.timeOfDay,
    this.dueHoursAfterScheduled,
    this.repeatEveryDays,
    this.repeatCount,
    this.metadataDefaults = const <String, dynamic>{},
  });

  final String templateId;
  final TaskType type;
  final String title;
  final String subtitle;
  final TaskPriority priority;
  final String deeplinkRoute;
  final String phase;
  final int relativeDay;
  final String timeOfDay;
  final int? dueHoursAfterScheduled;
  final int? repeatEveryDays;
  final int? repeatCount;
  final Map<String, dynamic> metadataDefaults;
}

const List<TaskTemplate> carePlanTemplates = <TaskTemplate>[
  TaskTemplate(
    templateId: 'preop_documents',
    type: TaskType.checklist,
    title: 'Unterlagen prüfen',
    subtitle: 'Versichertenkarte und Befunde bereitlegen',
    priority: TaskPriority.high,
    deeplinkRoute: '/packing',
    phase: 'preop',
    relativeDay: -2,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 12,
  ),
  TaskTemplate(
    templateId: 'preop_companion',
    type: TaskType.message,
    title: 'Begleitperson informieren',
    subtitle: 'Anfahrt und Treffpunkt abstimmen',
    priority: TaskPriority.normal,
    deeplinkRoute: '/doctor-questions',
    phase: 'preop',
    relativeDay: -1,
    timeOfDay: '18:00',
    dueHoursAfterScheduled: 4,
  ),
  TaskTemplate(
    templateId: 'preop_bag',
    type: TaskType.checklist,
    title: 'Klinik-Tasche packen',
    subtitle: 'Dokumente, Kleidung und Ladegerät einpacken',
    priority: TaskPriority.high,
    deeplinkRoute: '/packing',
    phase: 'preop',
    relativeDay: -1,
    timeOfDay: '20:00',
    dueHoursAfterScheduled: 10,
  ),
  TaskTemplate(
    templateId: 'opday_admission',
    type: TaskType.appointment,
    title: 'Aufnahme',
    subtitle: 'Bitte pünktlich in der Klinik melden',
    priority: TaskPriority.critical,
    deeplinkRoute: '/appointment',
    phase: 'opday',
    relativeDay: 0,
    timeOfDay: '07:00',
    dueHoursAfterScheduled: 2,
    metadataDefaults: <String, dynamic>{'milestone': 'Aufnahme'},
  ),
  TaskTemplate(
    templateId: 'opday_fasting',
    type: TaskType.checklist,
    title: 'Nüchternheit prüfen',
    subtitle: 'Nichts essen oder trinken laut Anweisung',
    priority: TaskPriority.critical,
    deeplinkRoute: '/checklist',
    phase: 'opday',
    relativeDay: 0,
    timeOfDay: '06:00',
    dueHoursAfterScheduled: 2,
  ),
  TaskTemplate(
    templateId: 'opday_info',
    type: TaskType.message,
    title: 'OP-Infos bestätigen',
    subtitle: 'Offene Rückfragen mit Team klären',
    priority: TaskPriority.high,
    deeplinkRoute: '/doctor-questions',
    phase: 'opday',
    relativeDay: 0,
    timeOfDay: '08:30',
    dueHoursAfterScheduled: 3,
  ),
  TaskTemplate(
    templateId: 'opday_mobilization',
    type: TaskType.custom,
    title: 'Erste Mobilisation',
    subtitle: 'Mit Unterstützung kurz aufsetzen/aufstehen',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'opday',
    relativeDay: 0,
    timeOfDay: '18:00',
    dueHoursAfterScheduled: 6,
  ),
  TaskTemplate(
    templateId: 'week1_wound_photo',
    type: TaskType.wound,
    title: 'Wundfoto aufnehmen',
    subtitle: 'Foto für Verlauf dokumentieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/wound-editor',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '19:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 8,
  ),
  TaskTemplate(
    templateId: 'week1_pain_score',
    type: TaskType.custom,
    title: 'Schmerzscore erfassen',
    subtitle: 'Schmerzlevel in der App eintragen',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '12:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 8,
  ),
  TaskTemplate(
    templateId: 'week1_vitals',
    type: TaskType.custom,
    title: 'Vitalwerte prüfen',
    subtitle: 'Puls/Temperatur kurz notieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 8,
  ),
  TaskTemplate(
    templateId: 'week1_dressing',
    type: TaskType.wound,
    title: 'Verbandkontrolle',
    subtitle: 'Verbandzustand prüfen und dokumentieren',
    priority: TaskPriority.high,
    deeplinkRoute: '/wound-editor',
    phase: 'week1',
    relativeDay: 2,
    timeOfDay: '10:00',
    dueHoursAfterScheduled: 8,
  ),
  TaskTemplate(
    templateId: 'meds_morning',
    type: TaskType.meds,
    title: 'Medikation einnehmen',
    subtitle: 'Morgendosis laut Plan',
    priority: TaskPriority.high,
    deeplinkRoute: '/meds',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '08:00',
    dueHoursAfterScheduled: 2,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'meds_midday',
    type: TaskType.meds,
    title: 'Medikation einnehmen',
    subtitle: 'Mittagsdosis laut Plan',
    priority: TaskPriority.high,
    deeplinkRoute: '/meds',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '13:00',
    dueHoursAfterScheduled: 2,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'meds_evening',
    type: TaskType.meds,
    title: 'Medikation einnehmen',
    subtitle: 'Abenddosis laut Plan',
    priority: TaskPriority.high,
    deeplinkRoute: '/meds',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '20:00',
    dueHoursAfterScheduled: 2,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  // ── Woche 1: Zusätzliche tägliche Nachsorge ──────────────────────
  TaskTemplate(
    templateId: 'week1_compression',
    type: TaskType.checklist,
    title: 'Kompressionsstrümpfe prüfen',
    subtitle: 'Sitz und Zustand der Strümpfe kontrollieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '07:30',
    dueHoursAfterScheduled: 4,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'week1_leg_exercises',
    type: TaskType.custom,
    title: 'Beinübungen durchführen',
    subtitle: 'Füße kreisen, Beine anspannen – Thromboseprophylaxe',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '10:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'week1_breathing',
    type: TaskType.custom,
    title: 'Atemübungen',
    subtitle: '5–10 tiefe Atemzüge zur Lungenpflege',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '14:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week1_hydration',
    type: TaskType.checklist,
    title: 'Trinkmenge prüfen',
    subtitle: 'Mindestens 1,5 Liter Flüssigkeit am Tag',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '15:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'week1_mobilization',
    type: TaskType.custom,
    title: 'Kurz aufstehen & bewegen',
    subtitle: 'Langsam mobilisieren – auch kleine Schritte zählen',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 1,
    timeOfDay: '11:00',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week1_nutrition',
    type: TaskType.nutrition,
    title: 'Ernährung dokumentieren',
    subtitle: 'Leichte Kost bevorzugen, Protein nicht vergessen',
    priority: TaskPriority.low,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '18:30',
    dueHoursAfterScheduled: 6,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week1_redflags',
    type: TaskType.checklist,
    title: 'Warnsignale prüfen',
    subtitle: 'Fieber, Rötung, Schwellung, starke Schmerzen?',
    priority: TaskPriority.high,
    deeplinkRoute: '/checklist',
    phase: 'week1',
    relativeDay: 0,
    timeOfDay: '21:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  // ── Woche 2: Tägliche Nachsorge (Tag 8–14) ──────────────────────
  TaskTemplate(
    templateId: 'week2_walk',
    type: TaskType.custom,
    title: 'Spaziergang machen',
    subtitle: 'Täglich etwas weiter gehen – Kreislauf stärken',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week2',
    relativeDay: 8,
    timeOfDay: '10:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week2_wound_observe',
    type: TaskType.wound,
    title: 'Wunde beobachten',
    subtitle: 'Heilungsverlauf kontrollieren und dokumentieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/wound-editor',
    phase: 'week2',
    relativeDay: 8,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week2_pain',
    type: TaskType.custom,
    title: 'Schmerztagebuch',
    subtitle: 'Schmerzverlauf dokumentieren – wird es besser?',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week2',
    relativeDay: 8,
    timeOfDay: '12:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week2_physio',
    type: TaskType.custom,
    title: 'Physiotherapie-Übungen',
    subtitle: 'Übungen laut Anleitung durchführen',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'week2',
    relativeDay: 8,
    timeOfDay: '15:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week2_selfcheck',
    type: TaskType.custom,
    title: 'Tages-Check: Wie geht es mir?',
    subtitle: 'Kurz reflektieren – Fortschritte und Beschwerden notieren',
    priority: TaskPriority.low,
    deeplinkRoute: '/checklist',
    phase: 'week2',
    relativeDay: 8,
    timeOfDay: '20:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 7,
  ),
  TaskTemplate(
    templateId: 'week2_activation',
    type: TaskType.custom,
    title: 'Aktivierungsziel',
    subtitle: 'Kurzen Spaziergang nach Rücksprache durchführen',
    priority: TaskPriority.low,
    deeplinkRoute: '/checklist',
    phase: 'week2',
    relativeDay: 10,
    timeOfDay: '11:00',
    dueHoursAfterScheduled: 8,
  ),
  TaskTemplate(
    templateId: 'followup_day7',
    type: TaskType.appointment,
    title: 'Kontrolltermin',
    subtitle: 'Verlaufskontrolle in der Praxis',
    priority: TaskPriority.high,
    deeplinkRoute: '/appointment',
    phase: 'followup',
    relativeDay: 7,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 6,
    metadataDefaults: <String, dynamic>{'milestone': 'Kontrolltermin'},
  ),
  TaskTemplate(
    templateId: 'followup_day14',
    type: TaskType.appointment,
    title: 'Kontrolltermin',
    subtitle: 'Zweite Verlaufskontrolle',
    priority: TaskPriority.high,
    deeplinkRoute: '/appointment',
    phase: 'followup',
    relativeDay: 14,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 6,
    metadataDefaults: <String, dynamic>{'milestone': 'Kontrolltermin'},
  ),
  // ── Nachsorge: Woche 3–4 (Tag 15–30) ────────────────────────────
  TaskTemplate(
    templateId: 'followup_scar_care',
    type: TaskType.custom,
    title: 'Narbenpflege',
    subtitle: 'Narbe sanft eincremen und beobachten',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'followup',
    relativeDay: 14,
    timeOfDay: '09:30',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'followup_activity',
    type: TaskType.custom,
    title: 'Belastung steigern',
    subtitle: 'Aktivität langsam erhöhen – auf Körpersignale achten',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'followup',
    relativeDay: 15,
    timeOfDay: '10:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 1,
    repeatCount: 14,
  ),
  TaskTemplate(
    templateId: 'followup_wound_photo',
    type: TaskType.wound,
    title: 'Wundfoto aufnehmen',
    subtitle: 'Heilungsverlauf weiter dokumentieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/wound-editor',
    phase: 'followup',
    relativeDay: 15,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 8,
    repeatEveryDays: 3,
    repeatCount: 5,
  ),
  TaskTemplate(
    templateId: 'followup_weekly_check',
    type: TaskType.custom,
    title: 'Wöchentlicher Selbst-Check',
    subtitle: 'Heilungsfortschritt bewerten und dokumentieren',
    priority: TaskPriority.normal,
    deeplinkRoute: '/checklist',
    phase: 'followup',
    relativeDay: 15,
    timeOfDay: '18:00',
    dueHoursAfterScheduled: 12,
    repeatEveryDays: 7,
    repeatCount: 3,
  ),
  TaskTemplate(
    templateId: 'followup_day21',
    type: TaskType.appointment,
    title: 'Kontrolltermin',
    subtitle: 'Dritte Verlaufskontrolle',
    priority: TaskPriority.high,
    deeplinkRoute: '/appointment',
    phase: 'followup',
    relativeDay: 21,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 6,
    metadataDefaults: <String, dynamic>{'milestone': 'Kontrolltermin'},
  ),
  TaskTemplate(
    templateId: 'followup_day28',
    type: TaskType.appointment,
    title: 'Abschlusskontrolle',
    subtitle: 'Abschließende Untersuchung und Freigabe',
    priority: TaskPriority.high,
    deeplinkRoute: '/appointment',
    phase: 'followup',
    relativeDay: 28,
    timeOfDay: '09:00',
    dueHoursAfterScheduled: 6,
    metadataDefaults: <String, dynamic>{'milestone': 'Abschlusskontrolle'},
  ),
];
