// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhF4LZ5KF9cIr3BLfUHptEbFdi08PO1Y',
    appId: '1:877420872558:web:5b51372f926901471c777f',
    messagingSenderId: '877420872558',
    projectId: 'operationsbegleiter-860e7',
    authDomain: 'operationsbegleiter-860e7.firebaseapp.com',
    storageBucket: 'operationsbegleiter-860e7.firebasestorage.app',
    measurementId: 'G-C8N8ZZV974',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSoE3-t7LHZ9l-Fj4WVlGZ6tIXZh9Tjeo',
    appId: '1:877420872558:android:d63c27afb8dbb4af1c777f',
    messagingSenderId: '877420872558',
    projectId: 'operationsbegleiter-860e7',
    storageBucket: 'operationsbegleiter-860e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMD7oV9M6buvOxQ9wXGz97KB5dtv6wtU',
    appId: '1:877420872558:ios:e547608a1fd60a1f1c777f',
    messagingSenderId: '877420872558',
    projectId: 'operationsbegleiter-860e7',
    storageBucket: 'operationsbegleiter-860e7.firebasestorage.app',
    iosBundleId: 'com.example.operationsbegleiterV3',
    iosClientId: '877420872558-69njpg92enhn7qmhi42s1bikq1jig4ri.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMD7oV9M6buvOxQ9wXGz97KB5dtv6wtU',
    appId: '1:877420872558:ios:e547608a1fd60a1f1c777f',
    messagingSenderId: '877420872558',
    projectId: 'operationsbegleiter-860e7',
    storageBucket: 'operationsbegleiter-860e7.firebasestorage.app',
    iosBundleId: 'com.example.operationsbegleiterV3',
    iosClientId: '877420872558-69njpg92enhn7qmhi42s1bikq1jig4ri.apps.googleusercontent.com',
  );
}
