#!/usr/bin/env python3
"""Comprehensive fix: all remaining English values in app_de.arb (batch 5)."""
import json

ARB_PATH = "lib/l10n/app_de.arb"

FIXES = {
    # ── General UI ──────────────────────────────────────────────────────────
    "abmelden":                       "Abmelden",
    "alle":                           "Alle",
    "alleMarkieren":                  "Alle →",
    "aufgabenCount":                  "Aufgaben ({count})",
    "aufgabenCountSelected":          "{count} Aufgabe{suffix} ausgewählt",
    "calendarMonth":                  "Monat",
    "calendarWeek":                   "Woche",
    "cloneErstellt":                  '"{name}" erstellt',
    "commonBack":                     "OK",
    "csvExportieren":                 "CSV exportieren",
    "details":                        "Details",
    "discoverSubtitle":               "Alle Funktionen auf einen Blick",
    "discoverTitle":                  "Entdecken",
    "doctorHinzugefuegt":             "{name} wurde hinzugefügt",
    "einladungscode":                 "Einladungscode",
    "exportFehlgeschlagen":           "Export fehlgeschlagen.",
    "fehlerBeimErstellen":            "Fehler beim Erstellen.",
    "fehlerMitError":                 "Fehler: {error}",
    "fotosDurchsuchen":               "Fotos suchen (Datum, Notiz, Kategorie)…",
    "grundOptional":                  "Grund (optional)",
    "gueltigFuerTage":                "Gültig für {days} Tage",
    "hinweistextOptional":            "Hinweistext (optional)",
    "insights":                       "Einblicke",
    "keyIdOderUidSuchen":             "Key-ID oder Einlöser-UID suchen…",
    "keysErstellt":                   "{count} Keys erstellt",
    "losGehts":                       "Los geht's!",
    "medikamentWiederhergestellt":    "{name} wiederhergestellt",
    "mitarbeiterAction":              "Mitarbeiter {action}",
    "nachRolleFiltern":               "Nach Rolle filtern",
    "nameWurdeEntsperrt":             "{name} wurde entsperrt.",
    "neuerKey":                       "Neuer Key",
    "neuerName":                      "Neuer Name",
    "neuesPasswort":                  "Neues Passwort",
    "neuesPasswortFuer":              "Neues Passwort für {name}",
    "noSearchResults":                'Keine Ergebnisse für „{query}"',
    "opActions":                      "Aktionen",
    "opManageCaregivers":             "Begleiter\nverwalten",
    "opSymptomsLabel":                "Symptome",
    "placeholderLoading":             "Wird geladen…",
    "prioritaet":                     "Priorität",
    "recoveryFeed":                   "Genesungs-Feed",
    "rolleGeaendert":                 'Rolle geändert zu „{role}".',
    "searchHint":                     "Suchen…",
    "statistikenAktualisieren":       "Statistiken aktualisieren",
    "sucheNachTitelOderOrt":          "Nach Titel oder Ort suchen…",
    "suchenNameEmailUid":             "Suchen (Name, E-Mail oder UID)…",
    "tageVergeben":                   "{days} Tage gewährt",
    "uebungSuchen":                   "Übung suchen…",
    "verbindungTrennen":              "Verbindung trennen",
    "vorlage":                        "Vorlage",
    "vorlageErstellt":                'Vorlage „{name}" erstellt',
    "vorlageUebernommen":             '„{name}" in eigene Vorlagen kopiert',
    "vorlagenDurchsuchen":            "Vorlagen suchen...",
    "wochentage":                     "Wochentage",
    "zbBefund":                       "z.B. Befund",
    "zbUpdateWirdEingespielt":        "z.B. Update wird eingespielt…",
    "zeitfilterZuruecksetzen":        "Zeitfilter zurücksetzen",

    # ── Error messages ───────────────────────────────────────────────────────
    "errorAlreadyExists":             "Bereits vorhanden.",
    "errorCancelled":                 "Vorgang abgebrochen.",
    "errorEmailInUse":                "Diese E-Mail-Adresse wird bereits verwendet.",
    "errorFailedPrecondition":        "Aktion kann nicht durchgeführt werden.",
    "errorInvalidArgument":           "Ungültige Eingabe.",
    "errorInvalidEmail":              "Ungültige E-Mail-Adresse.",
    "errorNotFoundShort":             "Nicht gefunden.",
    "errorWrongPassword":             "Falsches Passwort.",

    # ── Month names ──────────────────────────────────────────────────────────
    "monthDecember":                  "Dezember",
    "monthFebruary":                  "Februar",
    "monthJanuary":                   "Januar",
    "monthJuly":                      "Juli",
    "monthJune":                      "Juni",
    "monthMarch":                     "März",
    "monthMay":                       "Mai",
    "monthOctober":                   "Oktober",

    # ── Weekday short names ──────────────────────────────────────────────────
    "weekdayShortFri":                "Fr",
    "weekdayShortMon":                "Mo",
    "weekdayShortSat":                "Sa",
    "weekdayShortSun":                "So",
    "weekdayShortThu":                "Do",
    "weekdayShortTue":                "Di",
    "weekdayShortWed":                "Mi",

    # ── Appointment form labels ──────────────────────────────────────────────
    "apptConfirmationPending":        "Bestätigung ausstehend",
    "apptCreatedBy":                  "Erstellt von {name}",
    "apptHintCustomMinutes":          "Minuten",
    "apptHintDoctor":                 "z.B. Dr. Müller",
    "apptHintLocation":               "z.B. Städtisches Klinikum",
    "apptHintLocationDetails":        "Details (Station, Zimmer)",
    "apptHintNote":                   "Optionale Notiz…",
    "apptLabelCustomMinutes":         "Minuten",
    "apptLabelDate":                  "Datum",
    "apptLabelEndTime":               "Endzeit",
    "apptLabelFurtherDetails":        "Weitere Details",
    "apptLabelFurtherReminders":      "Weitere Erinnerungen",
    "apptLabelLocation":              "Ort",
    "apptLabelNote":                  "Notiz",
    "apptLabelPriority":              "Priorität",
    "apptLabelReminder":              "Erinnerung",
    "apptLabelRepeatUntil":           "Bis",
    "apptLabelStartTime":             "Startzeit",
    "apptLabelTime":                  "Uhrzeit",
    "apptLabelTitleRequired":         "Titel *",
    "apptLabelType":                  "Typ",
    "apptMarkAsDone":                 "Als erledigt markieren",
    "apptMarkAsPlanned":              "Als geplant markieren",
    "apptNoResultsHint":              "Andere Suchbegriffe oder Filter verwenden.",
    "apptReminderMinutes":            "{minutes} Min. vorher",
    "apptRepeatUntilDate":            "(bis {date})",
    "apptSaving":                     "Wird gespeichert…",
    "apptTitleRequired":              "Titel ist erforderlich.",
    "apptYesterday":                  "Gestern",

    # ── Timeline ─────────────────────────────────────────────────────────────
    "timelineAddNoteContent":         "Inhalt (optional)",
    "timelineAddTaskDescription":     "Beschreibung (optional)",
    "timelineAddTaskTitle":           "Titel",
    "timelineDoneOfTotal":            "{done}/{total} erledigt",
    "timelineDue":                    "Fällig",
    "timelineDueAttention":           "{count} heute zu erledigen",
    "timelineFriday":                 "Freitag",
    "timelineMonday":                 "Montag",
    "timelineMyPlan":                 "Mein Plan",
    "timelineNextUp":                 "Weiter: {title}",
    "timelinePhasePersonal":          "Meine Einträge",
    "timelinePhasePreop":             "Vorbereitung",
    "timelinePhaseProgress":          "{done}/{total} erledigt",
    "timelinePhaseWeek1":             "Woche 1 · Heilung & Überwachung",
    "timelinePhaseWeek2":             "Woche 2 · Aktivierung",
    "timelineProgressPercent":        "{percent}% erledigt – weiter so!",
    "timelineRouteQuestions":         "Fragen & Notizen",
    "timelineRouteRehab":             "Reha",
    "timelineSaturday":               "Samstag",
    "timelineStickyDoneOfTotal":      "{done} von {total} erledigt",
    "timelineStickyDue":              "{count} fällig",
    "timelineStickyToday":            "{count} heute",
    "timelineStreakDays":             "{count} Tage",
    "timelineSunday":                 "Sonntag",
    "timelineThursday":               "Donnerstag",
    "timelineToday":                  "Heute",
    "timelineTomorrow":               "Morgen",
    "timelineTransportDriver":        "Fahrer",
    "timelineTransportNotes":         "Notizen",
    "timelineTransportOutbound":      "Hinfahrt (Uhrzeit / Treffpunkt)",
    "timelineTransportReturn":        "Rückfahrt (Uhrzeit / Treffpunkt)",
    "timelineTuesday":                "Dienstag",
    "timelineWednesday":              "Mittwoch",

    # ── Template task titles / subtitles ─────────────────────────────────────
    "templateFollowupActivityTitle":          "Aktivität steigern",
    "templateFollowupDay14Subtitle":          "Zweite Fortschrittskontrolle",
    "templateFollowupDay21Subtitle":          "Dritte Fortschrittskontrolle",
    "templateFollowupDay28Title":             "Abschlusskontrolle",
    "templateFollowupScarCareTitle":          "Narbenpflege",
    "templateFollowupWoundPhotoSubtitle":     "Heilungsfortschritt weiter dokumentieren",
    "templateFollowupWoundPhotoTitle":        "Wundfoto aufnehmen",
    "templateMedsEveningSubtitle":            "Abenddosis wie verordnet",
    "templateMedsMiddaySubtitle":             "Mittagsdosis wie verordnet",
    "templateMedsMorningSubtitle":            "Morgendosis wie verordnet",
    "templateOpdayAdmissionTitle":            "Aufnahme",
    "templateOpdayMobilizationTitle":         "Erste Mobilisierung",
    "templatePreopBagTitle":                  "Koffer packen",
    "templatePreopCompanionTitle":            "Begleitperson informieren",
    "templateWeek1BackPostureTitle":          "Rückenschutzhaltung",
    "templateWeek1BloodPressureTitle":        "Blutdruck messen",
    "templateWeek1BowelDiaryTitle":           "Stuhlgang dokumentieren",
    "templateWeek1BreathingCardioTitle":      "Atemübungen",
    "templateWeek1BreathingSpineSubtitle":    "Tiefe Atemzüge – Rücken gerade, sanft atmen",
    "templateWeek1BreathingSpineTitle":       "Atemübungen",
    "templateWeek1CardiacRehabSubtitle":      "Leichtes Gehen, Kreislauf langsam aufbauen",
    "templateWeek1CardiacRehabTitle":         "Herz-Reha-Übungen",
    "templateWeek1DietBuildupSubtitle":       "Leichte Kost, Schonkost → schrittweise steigern",
    "templateWeek1DietBuildupTitle":          "Kostaufbau",
    "templateWeek1DressingTitle":             "Verbandkontrolle",
    "templateWeek1HydrationSubtitle":         "Mindestens 1,5 Liter Flüssigkeit pro Tag",
    "templateWeek1LegExercisesSubtitle":      "Füße kreisen, Beine anspannen – Thromboseprophylaxe",
    "templateWeek1LegExercisesTitle":         "Beinübungen machen",
    "templateWeek1MobilizationSubtitle":      "Langsam mobilisieren – auch kleine Schritte zählen",
    "templateWeek1MobilizationTitle":         "Aufstehen & kurz bewegen",
    "templateWeek1NoStrainingSubtitle":       "Pressen vermeiden, seitwärts abrollen beim Aufstehen",
    "templateWeek1NoStrainingTitle":          "Bauchschutz",
    "templateWeek1RedFlagsSubtitle":          "Fieber, Rötung, Schwellung, starke Schmerzen?",
    "templateWeek1SpineStabilizationSubtitle":"Rumpfstabilisierung nach Anweisung – schrittweise steigern",
    "templateWeek1SpineStabilizationTitle":   "Stabilisierungsübungen",
    "templateWeek1SternumSubtitle":           "Nicht über 5 kg heben, Arme körpernah halten",
    "templateWeek1SternumTitle":              "Sternumschutz",
    "templateWeek1VitalsSubtitle":            "Puls/Temperatur kurz notieren",
    "templateWeek1WoundPhotoTitle":           "Wundfoto aufnehmen",
    "templateWeek2CardiacWalkSubtitle":       "Gehdistanz schrittweise steigern, Puls beobachten",
    "templateWeek2CardiacWalkTitle":          "Herz-Reha-Spaziergang",
    "templateWeek2DietNormalizeSubtitle":     "Verdauung beobachten – langsam auf Normalkost umstellen",
    "templateWeek2DietNormalizeTitle":        "Normale Ernährung aufbauen",
    "templateWeek2GaitSubtitle":              "Sicheres Gehen mit/ohne Hilfsmittel üben",
    "templateWeek2GaitTitle":                 "Gangschulung",
    "templateWeek2PainSubtitle":              "Schmerzverlauf dokumentieren – wird es besser?",
    "templateWeek2PhysioSubtitle":            "Übungen nach Anweisung durchführen",
    "templateWeek2PhysioTitle":               "Physiotherapie-Übungen",
    "templateWeek2WalkSubtitle":              "Täglich etwas weiter gehen – Kreislauf stärken",
    "templateWeek2WalkTitle":                 "Spazieren gehen",
    "templateWeek2WoundObserveTitle":         "Wunde beobachten",

    # ── Red flags ────────────────────────────────────────────────────────────
    "rfActiveBadge":                  "{count} aktiv",
    "rfActiveCount":                  "Aktiv ({count})",
    "rfActiveWarnings":               "Aktive Warnungen",
    "rfCheckStart":                   "Check starten",
    "rfEmergencyFollowSteps":         "Befolge diese Schritte der Reihe nach.",
    "rfEmergencyStep1Desc":           "Setzen oder hinlegen. Ruhig atmen.",
    "rfEmergencyStep1Title":          "Ruhe bewahren",
    "rfEscalate":                     "Eskalieren",
    "rfProFeatureSubtitle":           "Beschwerden manuell eingeben oder auf Pro upgraden.",
    "rfProFeatureTitle":              "Automatische Red-Flag-Erkennung ist eine Pro-Funktion.",
    "rfResolvedCount":                "Verlauf ({count})",
    "rfSeverityDescRed":              "Kritische Werte erkannt. Sofortige ärztliche Hilfe empfohlen.",
    "rfSeverityRed":                  "Rot",
    "rfSeverityTitleGreen":           "Alles OK",
    "rfSeverityTitleOrange":          "Erhöhtes Risiko",
    "rfSeverityTitleRed":             "Jetzt handeln",
    "rfSeverityTitleYellow":          "Leichte Auffälligkeit",
    "rfSeverityYellow":               "Gelb",
    "rfSourceManual":                 "Manuell",
    "rfSourceObservation":            "Beobachtung",
    "rfSourceTimeline":               "Timeline-Aufgabe",
    "rfSourceWarningCheck":           "Warnzeichen-Check",
    "rfStatusAcknowledged":           "Gesehen",
    "rfStatusEscalated":              "Eskaliert",
    "rfStatusMonitoring":             "Beobachtung",
    "rfStatusOpen":                   "Offen",
    "rfStatusResolved":               "Gelöst",

    # ── Warning screen ───────────────────────────────────────────────────────
    "warnCheckLabel":                 "Schnellcheck:",
    "warnItemBleedingSubtitle":       "Blut sickert schnell durch den Verband",
    "warnItemBleedingTitle":          "Starke Blutung",
    "warnItemBreathSubtitle":         "Atemnot oder Lufthunger",
    "warnItemBreathTitle":            "Atemnot",
    "warnItemFeverSubtitle":          "Temperatur über 38,5 °C",
    "warnItemPainSubtitle":           "Plötzlich zunehmend, nicht kontrollierbar",
    "warnItemRednessQ3":              "Gibt es Eiter oder Absonderungen?",
    "warnItemRednessTitle":           "Zunehmende Rötung / Schwellung",
    "warnItemSmellTitle":             "Übelriechendes Sekret",
    "warnLastCheck":                  "Letzter Check: {label} · {date}",
    "warnTitle":                      "Warnzeichen",

    # ── Bella AI ─────────────────────────────────────────────────────────────
    "bellaActionCancelled":           "Abgebrochen",
    "bellaActionCreated":             "Eintrag erstellt ✓",
    "bellaActionStatusCancelled":     "{label} — abgebrochen",
    "bellaActionStatusCreated":       "{label} — erstellt",
    "bellaActionStatusFailed":        "{label} — fehlgeschlagen",
    "bellaBriefingHttpError":         "Fehler beim Erstellen des Briefings (HTTP {statusCode}).",
    "bellaChipKneeTep":               "Info zur Knie-TEP",
    "bellaChipLogBloodPressure":      "Blutdruck 120/80 erfassen",
    "bellaChipLogMedication":         "Ich habe gerade Ibuprofen genommen",
    "bellaChipLogPain":               "Schmerzen erfassen: Knie, Stufe 4",
    "bellaChipSymptomCheck":          "Symptom-Check starten",
    "bellaConsentAccepted":           "Zustimmung erteilt",
    "bellaConsentDeclined":           "Zustimmung abgelehnt",
    "bellaConsentTitle":              "Datenschutzhinweis",
    "bellaConsentYes":                "Ja, ich stimme zu",
    "bellaDailyUsage":                "{used} / {limit} Nachrichten heute",
    "bellaFeatureAftercare":          "Nachsorge",
    "bellaFeaturePatients":           "Patienten",
    "bellaFeatureTasks":              "Aufgaben",
    "bellaFeatureWarnings":           "Warnzeichen",
    "bellaGreeting":                  "Hallo! Ich bin Bella AI 🐰",
    "bellaProUpgrade":                "Jetzt auf Pro upgraden",
    "bellaSays":                      "Bella sagt:",
    "bellaWoundObservations":         "Beobachtungen",
}


def main():
    with open(ARB_PATH, encoding="utf-8") as f:
        data = json.load(f)

    fixed = 0
    skipped = []
    for key, german_val in FIXES.items():
        if key in data:
            data[key] = german_val
            fixed += 1
        else:
            skipped.append(key)

    with open(ARB_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Fixed {fixed} keys.")
    if skipped:
        print(f"Not found ({len(skipped)}): {skipped}")


if __name__ == "__main__":
    main()
